#
# Copyright 2016 HNSDFZ-OIER
#

CHESS_NONE = 0
CHESS_RED_KING = 1
CHESS_RED_GUARD = 2
CHESS_RED_BISHOP = 3
CHESS_RED_KNIGHT = 4
CHESS_RED_ROOK = 5
CHESS_RED_CANNON = 6
CHESS_RED_PAWN = 7
CHESS_BLACK_KING = 8
CHESS_BLACK_GUARD = 9
CHESS_BLACK_BISHOP = 10
CHESS_BLACK_KNIGHT = 11
CHESS_BLACK_ROOK = 12
CHESS_BLACK_CANNON = 13
CHESS_BLACK_PAWN = 14
